name: Build and Release Rust

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  build:
    name: Build on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            artifact_name: target/release/PrintCost
            asset_name: PrintCost-linux
          - os: windows-latest
            artifact_name: target/release/PrintCost.exe
            asset_name: PrintCost-windows.exe

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Rust Toolchain
        uses: dtolnay/rust-toolchain@stable

      - name: Rust Cache
        uses: swatinem/rust-cache@v2

      - name: Configure Static CRT for Windows
        if: matrix.os == 'windows-latest'
        shell: bash
        run: echo "RUSTFLAGS=-Ctarget-feature=+crt-static" >> $GITHUB_ENV

      - name: Build Binary
        run: cargo build --release

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.asset_name }}
          path: ${{ matrix.artifact_name }}

  release:
    name: Create Release
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download Linux Artifact
        uses: actions/download-artifact@v4
        with:
          name: PrintCost-linux
          path: artifacts/linux

      - name: Download Windows Artifact
        uses: actions/download-artifact@v4
        with:
          name: PrintCost-windows.exe
          path: artifacts/windows

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            artifacts/linux/PrintCost
            artifacts/windows/PrintCost.exe
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
